# Generated by Django 3.0.4 on 2020-03-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='identificaciones',
            new_name='identificacion',
        ),
    ]
